### ISSUE TITLE
`PHP Fatal error: Uncaught Http\Discovery\Exception\DiscoveryFailedException`

### ISSUE THREAD

**Issue by codepuncher** [dotmailer/dotdigital-for-wordpress#8]
Upgrading to https://github.com/dotmailer/dotdigital-signup-form/releases/tag/v6.0.3 causes fatal errors on sites using the plugin.

```log
2023/06/21 07:26:21 [error] 9019#9019: *3449761 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Http\Discovery\Exception\DiscoveryFailedException: Could not find resource using any discovery strategy. Find more information at http://docs.php-http.org/en/latest/discovery.html#common-errors
- No valid candidate found using strategy "Http\Discovery\Strategy\CommonClassesStrategy". We tested the following candidates: Nyholm\Psr7\Factory\HttplugFactory, Http\Message\MessageFactory\GuzzleMessageFactory, Http\Message\MessageFactory\DiactorosMessageFactory, Http\Message\MessageFactory\SlimMessageFactory.
- No valid candidate found using strategy "Http\Discovery\Strategy\CommonPsr17ClassesStrategy". We tested the following candidates: .
in /path/to/plugins/dotmailer-sign-up-widget/vendor/php-http/discovery/src/Exception/DiscoveryFailedException.php:41
Stack trace:
#0 /path/to/plugins/dotmailer-sign-up-widget/vendor/php-http/discovery/src/ClassDiscover" while reading response header from upstream, client: 82.153.21.255, server: www.example.co.uk, request: "POST /support-us/make-a-donation/single-donation/?amount=25.00 HTTP/2.0", upstream: "fastcgi://unix:/var/run/php8.1-fpm-example.sock:", host: "www.example.co.uk:23987", referrer: "https://www.example.co.uk/support-us/make-a-donation/single-donation/?amount=25.00"
```

I am guessing that perhaps a package is missing from your `vendor` directory in the published ZIP for the release?

Let me know if I can assist with tests.

Thanks

**Comment by sta1r** [comment]
@codepuncher sorry about this. Would have come back to you sooner also, but this issue wasn't forwarded. 

OK - I can't actually reproduce this using the tagged 6.0.3 files. Does it happen on widget submit? 

Does it still happen for you if set this in composer.json:
```
"config": {
        "allow-plugins": {
            "dealerdirect/phpcodesniffer-composer-installer": true,
            "php-http/discovery": false
        }
    }
```

**Comment by sta1r** [comment]
One other thing to try:
- remove the vendor folder in our plugin directory
- set the require like this:
```
"require": {
        "php": "^7.4 || ^8.0",
        "dotdigital/dotdigital-php": "2.0.0-RC1",
        "guzzlehttp/psr7": "^2.5",
        "guzzlehttp/guzzle": "^7.7",
        "php-http/curl-client": "^2.3",
        "php-http/message": "^1.16"
    },
```
- run `composer update --no-dev` in the plugin folder
- retry

**Comment by sta1r** [comment]
I've pushed up the above suggestions to a new branch: https://github.com/dotmailer/dotdigital-signup-form/tree/AM/216205-package-update

Perhaps you could try this out on your system at some point? Thanks

**Comment by sta1r** [comment]
@codepuncher Hi again - we've released a new version with namespace scoping. See https://github.com/dotmailer/dotdigital-for-wordpress/commit/a87afef79518912bfeab29d3b50d2ee1b78ba348. A namespace clash could have been responsible for your issue, based on your June 27 comment.
